return {
    "Lollypop Hub is warming up the kandy machine.",
    "Spinning the stick until the UI behaves.",
    "Loading tabs without waking the lag monster.",
    "Polishing the glass panels one pixel at a time.",
    "Kandy theme tastes better with reduced motion off.",
    "Dark theme is for people who load hubs at 3 AM.",
    "Blood theme looks dangerous but the buttons are still friendly.",
    "Sakura theme was approved by the pink pixel committee.",
    "Neon theme may be visible from another server.",
    "Minimal theme removed everything except the useful stuff.",
    "A lollypop is just a circle with ambition.",
    "The loading bar is moving. It is not just pretending.",
    "Small phone detected? The UI knows how to shrink.",
    "Drag lock exists because accidental movement is disrespectful.",
    "Edge snapping keeps the hub from escaping the screen.",
    "Low-performance mode tells the animations to calm down.",
    "Reduced-motion mode keeps the UI smooth without the extra movement.",
    "The kommand prefix is yours. The default is an exclamation mark.",
    "Type > help in the palette when your memory clocks out.",
    "Type !help in chat to see the kommand list.",
    "Partial player names work because nobody wants to type all that.",
    "Display names and usernames both count during player search.",
    "Use !to random when you trust chaos more than directions.",
    "Use !to nearest when walking feels unnecessary.",
    "Use !to furthest when personal space is the mission.",
    "Use !sit when standing has become too much work.",
    "Use !jump when the floor starts acting suspicious.",
    "Use !speed 50 when normal walking is moving disrespectfully slow.",
    "The emergency unload button is the big red exit without the drama.",
    "Notification history remembers what you ignored.",
    "Muted notifications still get saved in history.",
    "Progress notifications are legally required to look productive.",
    "Every setting gets a reset button because mistakes happen fast.",
    "Typed slider values exist for people who need exact numbers.",
    "Mobile keybinds become a draggable on-screen button.",
    "The command palette works on touch, mouse, and keyboard.",
    "Lazy-loaded tabs do not build until you actually open them.",
    "Debounced buttons ignore double taps before they start beefing.",
    "Safe callbacks keep one broken feature from killing the whole hub.",
    "Exact error reports are better than a button silently doing nothing.",
    "The player list refreshes because people never stay in one server.",
    "Avatar thumbnails are cached so they do not keep begging Roblox.",
    "The FPS viewer watches the frames so you do not have to.",
    "Memory numbers are not a personality test.",
    "The theme selector has more moods than the average group chat.",
    "Your accent kolor is saved because consistency matters.",
    "The logo has an easter egg. Seven clicks is a suspicious number.",
    "The footer knows the version even when everybody else forgets.",
    "The loader picked this message out of more than two hundred.",
    "The same loading message should not stalk you twice in a row.",
    "Kache is spelled with a K here. The performance still counts.",
    "Lollypop Hub does not skip leg day. It skips duplicate konnections.",
    "The sidebar gradient is doing more work than it gets credit for.",
    "Glassmorphism is just transparency wearing expensive clothes.",
    "A thin glowing border can make almost anything look official.",
    "Hover animations are tiny. Press animations are tinier.",
    "The UI can resize, but it still has boundaries.",
    "Phone, tablet, and desktop layouts are all invited.",
    "The iPhone mini is small, not forgotten.",
    "Android screens come in every shape known to mankind.",
    "Keyboard-safe text boxes try not to hide behind the keyboard.",
    "The notification volume slider is not a challenge.",
    "Opening sounds are optional because silence is valid.",
    "Seasonal themes are free decoration for the calendar.",
    "Halloween mode adds spooky pixels, not actual ghosts.",
    "Khristmas mode puts the kandy cane department on overtime.",
    "Valentine mode makes the accent kolor emotionally available.",
    "The music widget is not allowed to fight the notification sound.",
    "Tab transitions can slide without taking a road trip.",
    "The hub remembers its last settings when file functions exist.",
    "Konfig names should be useful. Config1 is not useful.",
    "Auto-save waits for changes instead of writing every frame.",
    "Rename your konfig before you forget what it does.",
    "Deleting a konfig is permanent, so the button does not rush you.",
    "The update checker checks versions, not your life choices.",
    "Supported-game status should be honest, not optimistic.",
    "Feature descriptions appear on hover or a long mobile hold.",
    "The logo is a lollypop, not a weather radar.",
    "The loading spinner is rotating with purpose.",
    "Particles are disabled in low-performance mode because frames matter.",
    "Bubbles, sparkles, and tiny lollypops signed the same contract.",
    "The UI is not oversized. Your old layout was just fearless.",
    "A smaller interface does not mean smaller features.",
    "The close button closes. The unload button cleans up.",
    "Destroying the UI and unloading the hub are not the same job.",
    "The chat kommand listener respects the prefix you selected.",
    "Changing the prefix helps when another admin script steals yours.",
    "Command history remembers what you typed, not what you meant.",
    "Up and down arrows are for desktop command history.",
    "Mobile command history lives in the suggestion list.",
    "The palette accepts commands with or without the chat prefix.",
    "Type > settings to jump straight to the settings tab.",
    "Type > lowperformance to make the fancy stuff sit down.",
    "Type > motion to toggle reduced motion.",
    "Type > unload when the hub needs to disappear correctly.",
    "Type > players to open the player tools.",
    "Type > notifications to inspect what the hub told you.",
    "Type > theme kandy when the current mood needs sugar.",
    "Type > theme dark when your eyes file a complaint.",
    "Type > theme neon when subtlety has left the server.",
    "Type > scale mini when screen space is expensive.",
    "Type > scale auto when you want the hub to decide.",
    "Type > draglock on before your thumb starts rearranging furniture.",
    "The nearest player is measured from your HumanoidRootPart.",
    "The furthest player must have a character to qualify.",
    "Random player excludes you because teleporting to yourself is boring.",
    "Sitting on a target uses their head as a very temporary chair.",
    "Kick only removes the local player. It is not an admin power.",
    "A custom kick message can contain spaces.",
    "WalkSpeed resets to sixteen when you ask nicely.",
    "JumpPower and JumpHeight depend on the game humanoid settings.",
    "Rejoin uses the current place and job when possible.",
    "Server hop still depends on the server list being available.",
    "The hub cannot fix a remote skript that deleted itself years ago.",
    "A dead URL is not a UI bug, even when the button looks guilty.",
    "Some skripts fail because the game updated before the skript did.",
    "Some skripts fail because another skript changed the same globals.",
    "The safe runner reports download, compile, and runtime separately.",
    "A downloaded skript is not executed until compilation succeeds.",
    "A compiled skript can still fail during runtime.",
    "Error history makes silent buttons less mysterious.",
    "The hub is loading. The server is probably doing something weird too.",
    "Roblox services are being asked politely.",
    "The UI library is counting its corners.",
    "The sidebar is choosing a gradient with confidence.",
    "The notification center is organizing future interruptions.",
    "The command registry is alphabetizing chaos.",
    "The player resolver is learning everybody's aliases.",
    "The config system is checking whether writefile exists.",
    "The loader is avoiding the same message as last time.",
    "The logo is melting artistically, not thermally.",
    "The progress bar has reached a legally meaningful percentage.",
    "The current percentage is mostly accurate and fully dramatic.",
    "The hub is almost ready to mind its business.",
    "One more tab and the kandy store opens.",
    "This message was selected by a table, not destiny.",
    "The randomizer has no favorites. Probably.",
    "Every lollypop eventually reaches the stick.",
    "A clean unload is worth more than ten destroy calls.",
    "The UI remembers that touch screens do not have hover.",
    "Long-press descriptions exist for mobile users.",
    "The resize handle is in the bottom-right corner minding its business.",
    "Screen-edge snapping only activates near the edge.",
    "The interface clamps itself so the close button stays reachable.",
    "Animations use tweens, not hopes and prayers.",
    "Low-performance mode disables blur before blaming your phone.",
    "The blur effect only exists while the hub is visible.",
    "Custom cursor mode is desktop-only because touch has no cursor.",
    "The lollypop cursor follows the mouse, not your dreams.",
    "Notification sounds respect mute and volume settings.",
    "Success is green. Errors are red. Warnings are loud yellow.",
    "Info notifications are blue because tradition won.",
    "The notification card can close itself without taking it personally.",
    "Progress cards can update instead of multiplying.",
    "One broken button should never freeze every other button.",
    "Button callbacks are debounced before execution.",
    "The error handler includes a traceback when the executor supports it.",
    "The hub can still run when file saving is unavailable.",
    "Configs are optional. Working defaults are not.",
    "The default prefix is ! because punctuation needed a job.",
    "Prefix changes are saved per executor session and file when possible.",
    "A blank prefix is rejected because every chat message would become a command.",
    "Player matching checks exact names before partial names.",
    "Ambiguous partial names choose the shortest matching result.",
    "Display names can contain spaces, so the resolver joins command arguments.",
    "The help list includes aliases and examples.",
    "Command aliases save typing without hiding the real name.",
    "The palette filters commands while you type.",
    "The mobile palette button stays near the screen edge.",
    "Pressing Enter executes the highlighted or typed command.",
    "The palette closes after a successful command by default.",
    "Error notifications keep the palette open so you can fix the command.",
    "The hub version is 9.4.0 until you change the version string.",
    "The changelog belongs inside the hub, not buried in a message.",
    "Update notes should say what changed and what broke.",
    "Supported games deserve a real status label.",
    "Unknown games are not automatically unsupported.",
    "The player count can change before the label finishes blinking.",
    "Avatar thumbnails are requested at a reasonable size.",
    "Cache misses happen. The placeholder still looks decent.",
    "The FPS counter averages frames instead of panicking every frame.",
    "Memory is shown in megabytes because bytes are rude.",
    "The performance widget updates slowly on purpose.",
    "A theme change should not recreate the entire hub.",
    "Accent changes update bound UI objects live.",
    "Seasonal mode can be disabled when October gets too loud.",
    "The kandy palette is the default because this is Lollypop Hub.",
    "The dark palette is easier on eyes and battery.",
    "The neon palette is easier to find and harder to ignore.",
    "The minimal palette keeps the glow on a short leash.",
    "The sakura palette understood the assignment.",
    "The blood palette came back cleaner than before.",
    "A setting reset only resets that setting, not your whole config.",
    "The reset button is small so it does not steal the row.",
    "Typed slider boxes accept numbers and clamp bad values.",
    "Dropdowns can refresh their option list after creation.",
    "Labels can update without rebuilding their section.",
    "Hidden controls stay searchable only when they are visible.",
    "Search ignores capitalization because that argument is pointless.",
    "Lazy tabs save startup time on giant hubs.",
    "The first tab builds immediately so you are not staring at nothing.",
    "Other tabs wait until you actually click them.",
    "A tab only builds once unless the hub explicitly rebuilds it.",
    "The command tab is useful even when every game skript is broken.",
    "The emergency button is useful especially when every game skript is broken.",
    "The loader is done talking soon.",
    "The kandy machine passed its startup check.",
    "The stick is attached. The logo is centered. We can proceed.",
    "The UI survived another loading message.",
    "The last few percent always act important.",
    "Almost loaded is still loading, but it sounds better.",
    "The hub is checking for duplicate copies before opening.",
    "Duplicate hubs cause duplicate listeners, and nobody asked for that.",
    "The unload routine clears the loaded flag for a clean reload.",
    "Reloading without cleanup is how ghost connections are born.",
    "The config folder is created only when the executor supports folders.",
    "JSON is doing paperwork behind the scenes.",
    "The command system does not need a separate admin script.",
    "The command system only controls your local player.",
    "Teleport commands need a loaded target character.",
    "Distance commands skip players missing a root part.",
    "The sit command waits for both characters to exist.",
    "The jump command asks the Humanoid to change state.",
    "The speed command clamps extreme values before the game gets offended.",
    "The kick command uses the full remaining text as its message.",
    "The help command is the least dramatic and most useful command.",
    "The clearhistory command gives notifications amnesia.",
    "The notifytest command exists because settings need proof.",
    "The fps command reports the current average.",
    "The memory command reports the client memory estimate.",
    "The unload command should be used before executing a fresh copy.",
    "The reload command can only reload from the configured loader URL.",
    "A loader URL can be changed through getgenv before execution.",
    "The random facts URL can also be overridden through getgenv.",
    "External message tables must return a Lua table.",
    "An empty external table falls back to built-in messages.",
    "A bad message URL will not stop the hub from loading.",
    "The recent-message list prevents immediate repeats.",
    "The shuffle bag resets only after every message gets a turn.",
    "This message may never appear again until the bag resets.",
    "That is statistically dramatic, not emotionally personal.",
    "Lollypop Hub is now checking the final screws.",
    "The final screw was a variable name. It is fine now.",
    "The loading sound is optional and volume-controlled.",
    "No sound is played when notifications are muted.",
    "The opening sound destroys itself after playback.",
    "Particles recycle instead of multiplying forever.",
    "Low-performance mode skips the particle loop entirely.",
    "Reduced motion keeps the logo still and the progress readable.",
    "The loader frame scales down on narrow screens.",
}
